defmodule ICal.Event do
  defstruct uid: nil,
            dtstamp: nil,
            summary: nil,
            description: nil,
            location: nil,
            dtstart: nil,
            dtend: nil,
            class: nil,
            created: nil,
            geo: nil,
            last_mod: nil,
            organizer: nil,
            priority: nil,
            seq: nil,
            status: nil,
            transp: nil,
            url: nil,
            recurid: nil,
            rrule: nil,
            attach: nil,
            attendee: nil,
            categories: nil,
            comment: nil,
            contact: nil,
            exdate: nil,
            rstatus: nil,
            related: nil,
            resources: nil,
            rdate: nil,
            x_prop: nil,
            iana_prop: nil
end
